name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build RosBE
      run: sudo ./RosBE-Builder.sh
    - name: Create Tar.gz archive
      run: tar -czf /tmp/RosBE-Unix-Binary.tar.gz /usr/local/RosBE
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RosBE-Unix-Binary
        # path: /usr/local/RosBE/
        path: /tmp/RosBE-Unix-Binary.tar.gz
    
  tag:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Create/Update latest tag
      uses: rickstaa/action-create-tag@v1
      id: "tag_create"
      with:
        tag: "latest"
        tag_exists_error: false
        force_push_tag: true
        message: "Latest release"
    
  release:
    runs-on: ubuntu-latest
    needs: tag
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: RosBE-Unix-Binary
        path: artifact-dir
    - run: ls -R artifact-dir
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: artifact-dir/RosBE-Unix-Binary.tar.gz
        tag: "latest"
        bodyFile: README
        replacesArtifacts: true
